FROM php:8.3-fpm  

RUN apt-get update && apt-get install -y \
    zip unzip curl git libonig-dev libxml2-dev \
    libzip-dev libicu-dev locales \
    && docker-php-ext-install \
    pdo_mysql \
    mbstring \
    exif \
    pcntl \
    bcmath \
    intl \
    zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer