
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: mihara-hp-app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: mihara-hp-nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mihara-hp-mysql
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: mihara-hp-phpmyadmin
    restart: always
    ports:
      - "8181:80"  # ← ここを8081 → 8181に変更
    environment:
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: secret
    depends_on:
      - db

  node:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run build"

volumes:
  db_data: